version: 1.0.{build}
    
build:
  verbosity: minimal
  project: FindAndBook.API\FindAndBook.API.sln

before_build:
- ps: nuget restore ./FindAndBook.API/FindAndBook.API.sln

after_test: 
  - FindAndBook.API\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"FindAndBook.API\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"/domain:single  FindAndBook.API\FindAndBook.Tests\bin\Debug\FindAndBook.Tests.dll -output:coverage.xml
  
  - FindAndBook.API\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml