namespace FindAndBook.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Removeautogeneratedrestaurantid : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.BookedTables", "BookingId", "dbo.Bookings");
            DropPrimaryKey("dbo.Bookings");
            AlterColumn("dbo.Bookings", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.Bookings", "Id");
            AddForeignKey("dbo.BookedTables", "BookingId", "dbo.Bookings", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.BookedTables", "BookingId", "dbo.Bookings");
            DropPrimaryKey("dbo.Bookings");
            AlterColumn("dbo.Bookings", "Id", c => c.Guid(nullable: false, identity: true));
            AddPrimaryKey("dbo.Bookings", "Id");
            AddForeignKey("dbo.BookedTables", "BookingId", "dbo.Bookings", "Id", cascadeDelete: true);
        }
    }
}
